[id='configuring-servers_{context}']
= Customizing {brandname} Server configuration

[role="_abstract"]
Apply custom `deploy.infinispan` values to {brandname} clusters that configure the Cache Manager and underlying server mechanisms like security realms or Hot Rod and REST endpoints.

[IMPORTANT]
====
You must always provide a complete {brandname} Server configuration when you modify `deploy.infinispan` values.
====

[NOTE]
====
Do not modify or remove the default "metrics" configuration if you want to use monitoring capabilities for your {brandname} cluster.
====

.Procedure

Modify {brandname} Server configuration as required:

* Specify configuration values for the Cache Manager with `deploy.infinispan.cacheContainer` fields.
+
For example, you can create caches at startup with any {brandname} configuration or add cache templates and use them to create caches on demand.

* Configure security authorization to control user roles and permissions with the `deploy.infinispan.cacheContainer.security.authorization` field.
* Select one of the default JGroups stacks or configure cluster transport with the `deploy.infinispan.cacheContainer.transport` fields.
* Configure {brandname} Server endpoints with the `deploy.infinispan.server.endpoints` fields.
* Configure {brandname} Server network interfaces and ports with the `deploy.infinispan.server.interfaces` and `deploy.infinispan.server.socketBindings` fields.
* Configure {brandname} Server security mechanisms with the `deploy.infinispan.server.security` fields.
