//Downstream content only
[id='installing-helm-chart-command-line_{context}']
= Installing the Helm chart on the command line

[role="_abstract"]
Use the `helm` and `oc` clients to create scripts that deploy {brandname} clusters on {openshiftshort}.

.Prerequisites

* Have access to an {openshiftshort} cluster and an `oc` client.
* Install the `helm` client.
* Add the link:{helm_chart_repo_readme}[{openshiftshort} Helm Charts repository].

.Procedure

. Create a values file for your {brandname} cluster that you can pass to the Helm chart.
+
For example, the following values file creates a cluster with two nodes:
+
[source,options="nowrap",subs=attributes+]
----
$ cat > datagrid-values.yaml<<EOF
include::yaml/infinispan-values.yaml[]
EOF
----
+
[TIP]
====
To find descriptions for each of the {brandname} values, refer to the link:{helm_chart_readme}[{brandname} chart README].
====
+
. Install the {brandname} chart and specify the values file for your cluster.
+
[source,options="nowrap",subs=attributes+]
----
$ helm install infinispan redhat-charts/datagrid -f datagrid-values.yaml
----

.Verification

Watch the pods to ensure all nodes in the {brandname} cluster are created successfully.

[source,options="nowrap",subs=attributes+]
----
$ oc get pods -w
----
