[id='server-configuration-values_{context}']
= {brandname} Server configuration values

[role="_abstract"]
{brandname} Server configuration values let you do the following:

* Create caches at startup with any {brandname} configuration.
* Add cache templates and use them to create caches on demand.
* Specify one of the default JGroups stacks.
* Define {brandname} Server security realms.
* Configure {brandname} Server endpoints with Hot Rod and REST connectors.

{brandname} Server configuration includes the `cacheContainer` fields in addition to `interfaces`, `socketBindings`, `endpoints`, and `security` fields.

[IMPORTANT]
====
You must always provide a complete {brandname} Server configuration when you modify `deploy.infinispan` values.
====

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/deploy_infinispan.yaml[]
----

[discrete]
== {brandname} cache configuration

.{brandname} cache
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/cache_manager_caches.yaml[]
----

.Cache template
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/cache_manager_cache_templates.yaml[]
----

[discrete]
== Cluster transport

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/jgroups_default.yaml[]
----

[discrete]
== {brandname} Server configuration

[IMPORTANT]
====
Do not modify or remove the following default configuration to avoid loss of service with your {brandname} cluster:

* "metrics" security realm.
* "metrics" endpoint.
* "default" or "metrics" socket bindings.
====

[NOTE]
====
The {brandname} chart does not currently support TLS/SSL security realms and encrypted client connections.
You cannot configure trust store realms.
====

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/server_configuration.yaml[]
----

[role="_additional-resources"]
.Additional resources
* link:{server_docs}[{brandname} Server Guide]
* link:{config_docs}[Configuring {brandname}]
