deploy:
  infinispan:
    server:
      security:
        credentialStores:
          - name: credentials
            path: internal-credentials.pfx
            clearTextCredential:
              clearText: "secret"
