apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-ping" (include "infinispan-helm-charts.name" .) }}
  annotations:
  {{- include "infinispan-helm-charts.annotations" . | nindent 4 }}
  labels:
    app: infinispan-service-ping
    clusterName: {{ include "infinispan-helm-charts.name" . }}
    {{- include "infinispan-helm-charts.labels" . | nindent 4 }}
    {{- include "infinispan-helm-charts.svcLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8888
      protocol: TCP
      name: infinispan
  selector:
    {{- include "infinispan-helm-charts.selectorLabels" . | nindent 4 }}
