{{- if not .Values.security.secretName }}
  {{- if .Release.IsInstall }}
  {{- $password := randAlphaNum 8 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-generated-secret" (include "infinispan-helm-charts.name" .) }}
  labels:
    app: infinispan-secret-identities
  {{- include "infinispan-helm-charts.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": no-update
type: Opaque
stringData:
  username: monitor
  password: {{ $password }}
  {{- if .Values.security.batch }}
  identities-batch: |-
    {{- .Values.security.batch | trim | nindent 4 }}
    user create monitor -p {{ $password }} --users-file monitor-users.properties --groups-file monitor-groups.properties
  {{- else }}
  identities-batch: |-
    user create developer -p {{ $password }} -g admin
    user create monitor -p {{ $password }} --users-file monitor-users.properties --groups-file monitor-groups.properties
    {{- end }}
    {{- end }}
  {{- end }}