{{- if not .Values.security.secretName }}
  {{- if .Release.IsInstall }}
  {{- $password := randAlphaNum 8 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-generated-secret" (include "infinispan-helm-charts.name" .) }}
  labels:
    app: infinispan-secret-identities
  {{- include "infinispan-helm-charts.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": no-update
type: Opaque
stringData:
  {{- if .Values.security.identities }}
  {{- $identities := fromYaml .Values.security.identities }}
  {{- $firstIdentity := index $identities.credentials 0 }}
  username: {{ $firstIdentity.username }}
  password: {{ $firstIdentity.password }}
  identities-batch: |-
    {{- range $c := $identities.credentials }}
    user create {{ $c.username }} -p {{ $c.password }}{{range $c.roles}} -g {{.}}{{end}}
    {{- end }}
  {{- else }}
  username: developer
  password: {{ $password }}
  identities-batch: |-
    user create developer -p {{ $password }} -g admin
    {{- end }}
    {{- end }}
  {{- end }}