{{- if not .Values.deploy.security.secretName }}
  {{- if .Release.IsInstall }}
  {{- $password := randAlphaNum 8 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infinispan-helm-charts.secret" . }}
  labels:
    app: infinispan-secret-identities
  {{- include "infinispan-helm-charts.labels" . | nindent 4 }}
  annotations:
  {{- include "infinispan-helm-charts.annotations" . | nindent 4 }}
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  username: monitor
  password: {{ $password }}
  {{- if .Values.deploy.security.batch }}
  identities-batch: |-
    {{- .Values.deploy.security.batch | trim | nindent 4 }}
    user create monitor -p {{ $password }} --users-file metrics-users.properties --groups-file metrics-groups.properties
  {{- else }}
  identities-batch: |-
    user create developer -p {{ $password }} -g admin
    user create monitor -p {{ $password }} --users-file metrics-users.properties --groups-file metrics-groups.properties
    {{- end }}
    {{- end }}
  {{- end }}