name: Testsuite
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v3.4
        id: install
      - name: Lint
        run: helm lint
      - uses: engineerd/setup-kind@v0.5.0
        name: Kind install
        with:
          version: "v0.11.0"
          image: kindest/node:v1.18.19@sha256:530378628c7c518503ade70b1df698b5de5585dcdba4f349328d986b8849b1ee
      - name: Display cluster settings
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Testing
        run: |
            kubectl create namespace helm-test
            helm install example-infinispan . -n helm-test --set deploy.replicas=2
            kubectl wait --for=condition=Ready pods -lapp=infinispan-pod -n helm-test --timeout=300s